import com.example.demo.entity.Land;
import com.example.demo.prices.TypePrice;
import com.example.demo.prices.MediaPrice;
import com.example.demo.prices.SizePrice;
import com.example.demo.common.MediaEnum;

global com.example.demo.prices.TypePrice typePrice;
global com.example.demo.prices.MediaPrice mediaPrice;
global com.example.demo.prices.SizePrice sizePrice;

rule "Power price"
    when
        Land(media contains MediaEnum.POWER.getName())
    then
        mediaPrice.setPrice(1000.0);
end

rule "Water price"
    when
        Land(media contains MediaEnum.WATER.getName())
    then
        mediaPrice.setPrice(2000.0);
end

rule "Gas price"
    when
        Land(media contains MediaEnum.GAS.getName())
    then
        mediaPrice.setPrice(3000.0);
end

rule "Sewage price"
    when
        Land(media contains MediaEnum.SEWER.getName())
    then
        mediaPrice.setPrice(4000.0);
end

rule "Multiple Utilities price"
    when
        Land($media : media)
    then

        if ($media.contains(MediaEnum.POWER.getName()) && $media.contains(MediaEnum.WATER.getName())) {
            mediaPrice.setPrice(3000.0);
        }
        if ($media.contains(MediaEnum.POWER.getName()) && $media.contains(MediaEnum.GAS.getName())) {
            mediaPrice.setPrice(4000.0);
        }
        if ($media.contains(MediaEnum.POWER.getName()) && $media.contains(MediaEnum.SEWER.getName())) {
            mediaPrice.setPrice(5000.0);
        }
        if ($media.contains(MediaEnum.WATER.getName()) && $media.contains(MediaEnum.GAS.getName())) {
            mediaPrice.setPrice(5000.0);
        }
        if ($media.contains(MediaEnum.WATER.getName()) && $media.contains(MediaEnum.SEWER.getName())) {
            mediaPrice.setPrice(6000.0);
        }
        if ($media.contains(MediaEnum.GAS.getName()) && $media.contains(MediaEnum.SEWER.getName())) {
            mediaPrice.setPrice(7000.0);
        }
        if ($media.contains(MediaEnum.POWER.getName()) && $media.contains(MediaEnum.WATER.getName())
            && $media.contains(MediaEnum.GAS.getName())) {
                    mediaPrice.setPrice(6000.0);
        }
        if ($media.contains(MediaEnum.POWER.getName()) && $media.contains(MediaEnum.WATER.getName())
            && $media.contains(MediaEnum.SEWER.getName())) {
                    mediaPrice.setPrice(7000.0);
        }
        if ($media.contains(MediaEnum.GAS.getName()) && $media.contains(MediaEnum.WATER.getName()) && $media.contains(MediaEnum.SEWER.getName())) {
                    mediaPrice.setPrice(9000.0);
        }
        if ($media.contains(MediaEnum.POWER.getName()) && $media.contains(MediaEnum.WATER.getName())
            && $media.contains(MediaEnum.GAS.getName()) && $media.contains(MediaEnum.SEWER.getName())) {
            mediaPrice.setPrice(10000.0);
        }
end
