import com.example.demo.entity.Land;
import com.example.demo.common.CityEnum;

global com.example.demo.prices.CityPrice cityPrice;

rule "Bialystok price"
    when
        Land(city == CityEnum.BIALYSTOK.getName())
    then
    cityPrice.setMultiplier(2);
end

rule "Warszawa price"
    when
        Land(city == CityEnum.WARSAW.getName())
    then
    cityPrice.setMultiplier(4);
end

rule "Poznan price"
    when
        Land(city == CityEnum.POZNAN.getName())
    then
    cityPrice.setMultiplier(3);
end

rule "Wroclaw price"
    when
        Land(city == CityEnum.WROCLAW.getName())
    then
    cityPrice.setMultiplier(3);
end