import com.example.demo.entity.Land;
import com.example.demo.prices.ShapePrice;

import com.example.demo.common.TotalPriceFact
global com.example.demo.common.TotalPriceFact totalPriceFact;

declare ShapePriceFact
    regular : boolean
    multiplier : double
end


rule "Define Shape Prices"
    no-loop
    when
        not ShapePriceFact()
    then
        insert(new ShapePriceFact(true, 1.2));
        insert(new ShapePriceFact(false, 0.8));
end


rule "Set Shape Price"
    when
        $land : Land($regular : regular)
        $priceFact : ShapePriceFact(regular == $regular, $multiplier : multiplier)
    then
        totalPriceFact.setShapeMultiplier($multiplier);
end

rule "Re-calculate totalPriceFact after shape update"
    salience -1
    when
        $totalPriceFact : TotalPriceFact(shapeMultiplier != null) from totalPriceFact
    then
        totalPriceFact.calculateTotalPrice();
end