import com.example.demo.entity.Land;
import com.example.demo.common.CityEnum;
import com.example.demo.prices.CityPrice;
import com.example.demo.common.CityMultiplier


import com.example.demo.common.TotalPriceFact
global com.example.demo.common.TotalPriceFact totalPriceFact;


rule "Define City Multipliers"
    no-loop
    when
        not CityMultiplier()
    then
        insert(new CityMultiplier("Bialystok", 2));
        insert(new CityMultiplier("Warszawa", 4));
        insert(new CityMultiplier("Poznan", 3));
        insert(new CityMultiplier("Wroclaw", 3));
end

rule "Set City Price Multiplier"
    when
        $land : Land($city : city)
        $multiplier : CityMultiplier(city == $city)
    then
        totalPriceFact.setCityMultiplier($multiplier.getMultiplier());
        totalPriceFact.setNeedRecalculation(true);
end