import com.example.demo.entity.Land;
import com.example.demo.common.MediaEnum;
import com.example.demo.prices.TypePrice;
import com.example.demo.prices.MediaPrice;
import com.example.demo.prices.SizePrice;
import com.example.demo.common.MediaPriceFact;
import com.example.demo.common.TotalPriceFact;

import java.util.Arrays;
import java.util.List;

global com.example.demo.common.TotalPriceFact totalPriceFact;


rule "Define Media Prices"
    no-loop
    when
        not MediaPriceFact()
    then
        insert(new MediaPriceFact(Arrays.asList("Prad"), 1000.0));
        insert(new MediaPriceFact(Arrays.asList("Woda"), 2000.0));
        insert(new MediaPriceFact(Arrays.asList("Gaz"), 3000.0));
        insert(new MediaPriceFact(Arrays.asList("Kanalizacja"), 4000.0));
        insert(new MediaPriceFact(Arrays.asList("Swiatlowod"), 1000.0));

end


rule "Sum Media Prices"
    when
        $land : Land($media : media)
        $priceFact : MediaPriceFact($mediaList : mediaList, $price : price)
        accumulate(
            $priceFact2 : MediaPriceFact($mediaList2 : mediaList, $price2 : price)
            and eval($media.containsAll($mediaList2)),
            $total : sum($price2)
        )
    then
        totalPriceFact.setMediaPrice((double)$total);

end

rule "Re-calculate totalPriceFact after media update"
    salience -1
    when
        $totalPriceFact : TotalPriceFact(mediaPrice != null) from totalPriceFact
    then
        totalPriceFact.calculateTotalPrice();
end