import com.example.demo.entity.Land;
import com.example.demo.common.CityEnum;
import com.example.demo.prices.CityPrice;
import com.example.demo.common.CityMultiplier

global com.example.demo.prices.CityPrice cityPrice;


rule "Define City Multipliers"
    no-loop
    when
        not CityMultiplier()
    then
        insert(new CityMultiplier("Bialystok", 2));
        insert(new CityMultiplier("Warszawa", 4));
        insert(new CityMultiplier("Poznan", 3));
        insert(new CityMultiplier("Wroclaw", 3));
end

rule "Set City Price Multiplier"
    when
        $land : Land($city : city)
        $multiplier : CityMultiplier(city == $city)
    then
        cityPrice.setMultiplier($multiplier.getMultiplier());
end
