import com.example.demo.entity.Land;
import com.example.demo.prices.ShapePrice;

global com.example.demo.prices.ShapePrice shapePrice;

declare ShapePriceFact
    regular : boolean
    multiplier : double
end


rule "Define Shape Prices"
    no-loop
    when
        not ShapePriceFact()
    then
        insert(new ShapePriceFact(true, 1.2));
        insert(new ShapePriceFact(false, 0.8));
end


rule "Set Shape Price"
    when
        $land : Land($regular : regular)
        $priceFact : ShapePriceFact(regular == $regular, $multiplier : multiplier)
    then
        shapePrice.setShapeMultiplier($multiplier);
end